### ISSUE TITLE
Issue running composer update

### ISSUE THREAD

**Issue by delahappy** [StudentAffairsUWM/Laravel-Shibboleth-Service-Provider#10]
My app is on laravel 4.2.  I have it working with shibb in dev but when I try to install it on my prod server I am getting an error.  I am trying to run composer update but it fails with the error below.  Any idea of how to resolve this dependency?

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v4.2.17
    - Conclusion: don't install laravel/framework v4.2.17
    - Conclusion: don't install laravel/framework v4.2.16
    - Conclusion: don't install laravel/framework v4.2.15
    - Conclusion: don't install laravel/framework v4.2.14
    - Conclusion: don't install laravel/framework v4.2.13
    - Conclusion: don't install laravel/framework v4.2.12
    - Conclusion: don't install laravel/framework v4.2.11
    - Conclusion: don't install laravel/framework v4.2.10
    - Conclusion: don't install laravel/framework v4.2.9
    - Conclusion: don't install laravel/framework v4.2.8
    - Conclusion: don't install laravel/framework v4.2.7
    - Conclusion: don't install laravel/framework v4.2.6
    - Conclusion: don't install laravel/framework v4.2.5
    - Conclusion: don't install laravel/framework v4.2.4
    - Conclusion: don't install laravel/framework v4.2.3
    - Installation request for saitswebuwm/shibboleth 1.0.0 -> satisfiable by saitswebuwm/shibboleth[1.0.0].
    - Conclusion: don't install laravel/framework v4.2.2
    - Conclusion: don't install laravel/framework v4.2.1
    - saitswebuwm/shibboleth 1.0.0 requires illuminate/support 5.0.* -> satisfiable by illuminate/support[v5.0.0, v5.0.4].
    - don't install illuminate/support v5.0.0|don't install laravel/framework v4.2.0
    - don't install illuminate/support v5.0.4|don't install laravel/framework v4.2.0
    - Installation request for laravel/framework 4.2.* -> satisfiable by laravel/framework[v4.2.0, v4.2.1, v4.2.10, v4.2.11, v4.2.12, v4.2.13, v4.2.14, v4.2.15, v4.2.16, v4.2.17, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9].

**Comment by saits-webteam** [comment]
Use version 0.5.6 of this plugin for Laravel 4.2

Sent from my iPhone

On Mar 11, 2015, at 1:03 PM, delahappy <notifications@github.com<mailto:notifications@github.com>> wrote:


My app is on laravel 4.2. I have it working with shibb in dev but when I try to install it on my prod server I am getting an error. I am trying to run composer update but it fails with the error below. Any idea of how to resolve this dependency?

Your requirements could not be resolved to an installable set of packages.

Problem 1
- Conclusion: remove laravel/framework v4.2.17
- Conclusion: don't install laravel/framework v4.2.17
- Conclusion: don't install laravel/framework v4.2.16
- Conclusion: don't install laravel/framework v4.2.15
- Conclusion: don't install laravel/framework v4.2.14
- Conclusion: don't install laravel/framework v4.2.13
- Conclusion: don't install laravel/framework v4.2.12
- Conclusion: don't install laravel/framework v4.2.11
- Conclusion: don't install laravel/framework v4.2.10
- Conclusion: don't install laravel/framework v4.2.9
- Conclusion: don't install laravel/framework v4.2.8
- Conclusion: don't install laravel/framework v4.2.7
- Conclusion: don't install laravel/framework v4.2.6
- Conclusion: don't install laravel/framework v4.2.5
- Conclusion: don't install laravel/framework v4.2.4
- Conclusion: don't install laravel/framework v4.2.3
- Installation request for saitswebuwm/shibboleth 1.0.0 -> satisfiable by saitswebuwm/shibboleth[1.0.0].
- Conclusion: don't install laravel/framework v4.2.2
- Conclusion: don't install laravel/framework v4.2.1
- saitswebuwm/shibboleth 1.0.0 requires illuminate/support 5.0.* -> satisfiable by illuminate/support[v5.0.0, v5.0.4].
- don't install illuminate/support v5.0.0|don't install laravel/framework v4.2.0
- don't install illuminate/support v5.0.4|don't install laravel/framework v4.2.0
- Installation request for laravel/framework 4.2.* -> satisfiable by laravel/framework[v4.2.0, v4.2.1, v4.2.10, v4.2.11, v4.2.12, v4.2.13, v4.2.14, v4.2.15, v4.2.16, v4.2.17, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9].

-

**Comment by delahappy** [comment]
Thanks, I am able to update now.  I have another question.  I can see in my shib logs that I am retrieving the attributes after authentication, however, when I debug the ShibbolethController, the $_SERVER array does not contain them.  Any idea where the handoff of those attributes could be failing?

**Comment by saits-webteam** [comment]
Sorry about the delay in responding.

Don’t check the server array. I believe Laravel has a function to get server variables… Request::server(‘eppn’) … Give that a try. For some reason, Laravel does something weird with the $_SERVER variables.

--
Christopher Maio – Lead Developer
Student Affairs IT Services - Bolton 288
Division of Student Affairs
University of Wisconsin-Milwaukee
(414) 979-9570

From: delahappy
Reply-To: StudentAffairsUWM/Laravel-Shibboleth-Service-Provider
Date: Wednesday, March 11, 2015 at 2:37 PM
To: StudentAffairsUWM/Laravel-Shibboleth-Service-Provider
Cc: saits-webteam
Subject: Re: [Laravel-Shibboleth-Service-Provider] Issue running composer update (#10)


Thanks, I am able to update now. I have another question. I can see in my shib logs that I am retrieving the attributes after authentication, however, when I debug the ShibbolethController, the $_SERVER array does not contain them. Any idea where the handoff of those attributes could be failing?

**Comment by delahappy** [comment]
I checked the Request::server("mail") and the attribute isn't there either.  I have this working on our redhat dev machine but we started using ubuntu and for some reason the attributes aren't passing to laravel on that server.  Any ideas where I should check for the problem?

Thanks for your help.

**Comment by delahappy** [comment]
Actually I found that there was an issue with the apache shib mod configuration.  Thanks again for your help.
