### ISSUE TITLE
Problem installing on a new project.

### ISSUE THREAD

**Issue by delahappy** [StudentAffairsUWM/Laravel-Shibboleth-Service-Provider#14]
I am starting a new laravel 5 project and when I try to run composer update I get this:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package studentaffairsuwm/shibboleth could not be found in a
ny version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your min
imum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> f
or more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further commo
n problems.
```

Here is my composer.json entry:

    "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.1.*",
        "studentaffairsuwm/shibboleth": "1.0.3"
    },

Any ideas?

**Comment by tdhsmith** [comment]
`1.0.3` landed this afternoon and it seems Packagist doesn't seem to have it yet. Hopefully that will fix itself shortly. 

If you need this immediately, you can temporarily set the version to `dev-master`, but be sure to switch it back to a specific version number in the future. (Otherwise a you might unknowingly download a new version you don't want, and it's hard to solve dependency conflicts with a constantly changing target version.)

**Comment by delahappy** [comment]
I tried that and I also tried 1.0.2 but both resulted in the same error.

**Comment by tdhsmith** [comment]
Well I fixed an issue with the internal version number and now I see it on Packagist, but I'm getting the error as well.

There are duplicates of the package for some reason -- [`studentaffairsuwm/shibboleth`](https://packagist.org/packages/studentaffairsuwm/shibboleth) and [`saitswebuwm/shibboleth`](https://packagist.org/packages/saitswebuwm/shibboleth) -- but they seem to be synced and both are giving the same result...

**Comment by tdhsmith** [comment]
Ok I think it was just a further delay in Packagist updates. I'm seeing both aliases working correctly with version `1.0.3`. If you're still having problems, let us know.

**Comment by delahappy** [comment]
It works for me now.  Thanks.
