### ISSUE TITLE
JWT tasks

### ISSUE THREAD

**Issue by tdhsmith** [StudentAffairsUWM/Laravel-Shibboleth-Service-Provider#16]
- [x] Fix security issues with JWTAuth refresh flow (cf. tymondesigns/jwt-auth#218)
- [x] Update essential function calls changed in JWTAuth 0.6.0
- [x] Trim out any `Session` logic in primary flow and convert to JWT when appropriate
- [x] JWT conversion & cleanup for local/emulated flows
- [x] ...

**Comment by cjmaio** [comment]
I'm going to close this task, @tdhsmith as I think this stuff was completed.
