### ISSUE TITLE
Step by Step Tutorial

### ISSUE THREAD

**Issue by Blitzbert** [StudentAffairsUWM/Laravel-Shibboleth-Service-Provider#17]
Hey there.
Does anybody know a step by step tutorial on how do implement the shibboleth login into my application?
I have a Shibboleth IDP and SP but idk howto implement this.

**Comment by michaeljs1990** [comment]
What about https://github.com/StudentAffairsUWM/Laravel-Shibboleth-Service-Provider#installation is not clear?

**Comment by cjmaio** [comment]
@Blitzbert 

What specifically do you have questions on? I'm more than willing to improve the documentation, but I'm curious as to where you're stuck.

If it's regarding setting up Shibboleth in general, that is outside of the scope of this plugin. This plugin assumes that a Shibboleth SP / IdP is setup and working. You can typically confirm this by going to:

http://yourserver.com/Shibboleth.sso/Session

**Comment by cjmaio** [comment]
I'm going to close this task, if you have any questions feel free to let us know! We will update this documentation as we are able to.
