### ISSUE TITLE
Laravel 5 support

### ISSUE THREAD

**Issue by yugen** [StudentAffairsUWM/Laravel-Shibboleth-Service-Provider#8]
I'm running into errors trying to get the package installed and configured.  After digging around in the code it looks like it's written for Laravel 4.  Is that correct?  If so, do you have any plans to update the package to support Laravel 5 any time soon?

**Comment by cjmaio** [comment]
Right now I have a load of projects at work, but we are planning on upgrading all applications to Laravel 5, which will require updating this plugin as well.

Long story short - yes, we do plan on doing it. I just don't know when, yet. I'd welcome pull requests though!

**Comment by yugen** [comment]
Thanks for the quick reply.  Like you, I've got a lot of projects in the air, and I'm new to Laravel development so I'm not sure I'll be able to be of too much help, but I'll fork and see what can be done.

**Comment by cjmaio** [comment]
Yeah, let's leave it open so I have a constant reminder to do it ;-)

**Comment by cjmaio** [comment]
The develop branch has an attempt at Laravel 5 compatibility. I decided to remove the built-in User and Group implementations, and instead as part of the publish process, provide some basic ones. Also not including the views, those can be created by whoever is using it.

**Comment by cjmaio** [comment]
So, I believe I've updated the plugin for Laravel 5. Let me know if you have any issues with it. I'm going to close this for now... but if there are any issues open up a new issue.

Thanks!
